{% set name = "napari-script-editor" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-script-editor-{{ version }}.tar.gz
  sha256: 77f1b3e145005b783f239cd0971978a114f26b3ca5c280bed6baf5228f9355ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - haesleinhuepf-pyqode.core >=2.15.5
    - haesleinhuepf-pyqode.python >=2.15.2
    - jedi >=0.18.0
    - napari
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy
    - python >=3.7

test:
  imports:
    - napari_script_editor
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-script-editor
  summary: A python script editor for napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - haesleinhuepf
